-- =========================================
-- CHAPTER 58 — TRUNCATE
-- Includes SQL Server, PostgreSQL, Oracle, MySQL examples
-- =========================================



-- =========================================
-- 🔹 SQL SERVER EXAMPLE
-- =========================================

CREATE TABLE Employee (
    EmployeeID INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(50),
    LastName NVARCHAR(50)
);
GO

INSERT INTO Employee (FirstName, LastName)
VALUES ('John','Smith'),
       ('Sarah','Johnson'),
       ('Mike','Brown');
GO

-- Remove all rows instantly
TRUNCATE TABLE Employee;
GO



-- =========================================
-- 🔹 POSTGRESQL EXAMPLE
-- =========================================

CREATE TABLE employee (
    employeeid SERIAL PRIMARY KEY,
    firstname VARCHAR(50),
    lastname VARCHAR(50)
);

INSERT INTO employee (firstname, lastname)
VALUES ('John','Smith'),
       ('Sarah','Johnson'),
       ('Mike','Brown');

-- Fast removal
TRUNCATE TABLE employee;



-- =========================================
-- 🔹 ORACLE EXAMPLE
-- =========================================

CREATE TABLE Employee (
    EmployeeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR2(50),
    LastName VARCHAR2(50)
);

INSERT INTO Employee (FirstName, LastName)
VALUES ('John','Smith');

INSERT INTO Employee (FirstName, LastName)
VALUES ('Sarah','Johnson');

-- Remove all rows
TRUNCATE TABLE Employee;



-- =========================================
-- 🔹 MYSQL EXAMPLE
-- =========================================

CREATE TABLE Employee (
    EmployeeID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50)
);

INSERT INTO Employee (FirstName, LastName)
VALUES ('John','Smith'),
       ('Sarah','Johnson'),
       ('Mike','Brown');

-- Fast bulk deletion
TRUNCATE TABLE Employee;



-- =========================================
-- 🔹 DELETE VS TRUNCATE COMPARISON
-- =========================================

-- Row-by-row deletion (fires triggers)
DELETE FROM Employee;

-- Bulk page deallocation (faster, resets identity)
TRUNCATE TABLE Employee;
